import { Permisos } from "./permisos.contract";
import { CargosPersonal } from "./persons.contract";
import { RolesPredefinidos } from "./roles.contract";

export type ConfiguracionRolPredefinido = {
  nombre: RolesPredefinidos;
  descripcion: string;
  permisos: Permisos[];
};

const PERMISOS_IMPRESORAS_USO_UNIVERSAL: Permisos[] = [
  Permisos.IMPRESORAS_VER,
  Permisos.IMPRESORAS_CONECTAR,
  Permisos.IMPRESORAS_DESCONECTAR,
  Permisos.IMPRESORAS_PROBAR,
];

export const PERMISOS_CRITICOS: Permisos[] = [
  Permisos.USUARIOS_CREAR,
  Permisos.USUARIOS_DESACTIVAR,
  Permisos.USUARIOS_ASIGNAR_ROLES,
  Permisos.ROLES_EDITAR_PERMISOS,
  Permisos.PRODUCTOS_EDITAR_PRECIO,
  Permisos.PRODUCTOS_VER_COSTO,
  Permisos.VENTAS_ANULAR,
  Permisos.CAJA_ABRIR,
  Permisos.CAJA_CERRAR_CUALQUIERA,
  Permisos.CAJA_EDITAR_TURNO_CERRADO,
  Permisos.FINANZAS_EDITAR,
  Permisos.INVENTARIO_AJUSTAR,
  Permisos.COMPRAS_APROBAR,
  Permisos.COMPRAS_ANULAR,
  Permisos.CONFIGURACION_SISTEMA_EDITAR,
  Permisos.CONFIGURACION_INTEGRACIONES_EDITAR,
  Permisos.AUDITORIA_EXPORTAR,
  Permisos.RESTAURANTE_SESION_LIBERAR_INCIDENCIA,
  Permisos.RESTAURANTE_CUENTA_COBRAR,
];

export const CARGOS_ROLES_SUGERIDOS: Record<CargosPersonal, RolesPredefinidos[]> = {
  [CargosPersonal.ADMINISTRADOR]: [RolesPredefinidos.ADMIN],
  [CargosPersonal.SUPERVISOR]: [RolesPredefinidos.SUPERVISOR],
  [CargosPersonal.OPERADOR_ATENCION_COMERCIAL]: [
    RolesPredefinidos.VENTAS,
    RolesPredefinidos.CAJERO,
  ],
  [CargosPersonal.ASISTENTE_OPERACIONES_COMERCIALES]: [RolesPredefinidos.OPERACIONES],
  [CargosPersonal.ENCARGADO_COMPRAS]: [RolesPredefinidos.COMPRAS],
  [CargosPersonal.ENCARGADO_INVENTARIO]: [RolesPredefinidos.INVENTARIO],
  [CargosPersonal.ENCARGADO_ALMACEN]: [
    RolesPredefinidos.INVENTARIO,
    RolesPredefinidos.OPERACIONES,
  ],
  [CargosPersonal.DESPACHADOR]: [
    RolesPredefinidos.OPERACIONES,
    RolesPredefinidos.VENTAS,
  ],
  [CargosPersonal.AUXILIAR_ADMINISTRATIVO]: [
    RolesPredefinidos.FINANZAS,
    RolesPredefinidos.SOLO_LECTURA,
  ],
  [CargosPersonal.CONTADOR]: [RolesPredefinidos.CONTADOR, RolesPredefinidos.FINANZAS],
  [CargosPersonal.AUDITOR]: [RolesPredefinidos.AUDITOR],
  [CargosPersonal.SOPORTE_TECNICO]: [RolesPredefinidos.SOPORTE_TECNICO],
  [CargosPersonal.SECRETARIO]: [RolesPredefinidos.SOLO_LECTURA],
  [CargosPersonal.ADMINISTRATIVO]: [RolesPredefinidos.FINANZAS],
  [CargosPersonal.REPONEDOR]: [RolesPredefinidos.OPERACIONES],
  [CargosPersonal.CAJERO]: [RolesPredefinidos.CAJERO],
  [CargosPersonal.VENDEDOR]: [RolesPredefinidos.VENDEDOR],
  [CargosPersonal.ANFITRION]: [RolesPredefinidos.GASTRONOMIA_ANFITRION],
  [CargosPersonal.MOZO_MESERO]: [RolesPredefinidos.GASTRONOMIA_MESERO],
  [CargosPersonal.CAPITAN_SALON]: [RolesPredefinidos.GASTRONOMIA_CAPITAN_SALON],
  [CargosPersonal.COCINERO]: [RolesPredefinidos.GASTRONOMIA_COCINERO],
  [CargosPersonal.JEFE_COCINA]: [RolesPredefinidos.GASTRONOMIA_JEFE_COCINA],
  [CargosPersonal.BARTENDER_ENCARGADO_BARRA]: [RolesPredefinidos.GASTRONOMIA_BARRA],
  [CargosPersonal.REPARTIDOR]: [],
};

export const CONFIGURACIONES_ROLES: Record<
  RolesPredefinidos,
  ConfiguracionRolPredefinido
> = {
  [RolesPredefinidos.ADMIN]: {
    nombre: RolesPredefinidos.ADMIN,
    descripcion: "Administrador del sistema con acceso completo",
    permisos: [...new Set(Object.values(Permisos))] as Permisos[],
  },
  [RolesPredefinidos.SUPERVISOR]: {
    nombre: RolesPredefinidos.SUPERVISOR,
    descripcion: "Supervision operativa con control de ventas, caja, inventario y reportes",
    permisos: [
      ...PERMISOS_IMPRESORAS_USO_UNIVERSAL,
      Permisos.DASHBOARD_VER,
      Permisos.DASHBOARD_OPERATIVO,
      Permisos.ALERTAS_VER,
      Permisos.PUNTO_VENTA_VER,
      Permisos.PUNTO_VENTA_CREAR,
      Permisos.PUNTO_VENTA_BUSCAR_PRODUCTOS,
      Permisos.PUNTO_VENTA_ASIGNAR_CLIENTE,
      Permisos.VENTAS_CREAR,
      Permisos.VENTAS_VER,
      Permisos.VENTAS_VER_TODAS,
      Permisos.VENTAS_VER_DETALLE,
      Permisos.VENTAS_EDITAR,
      Permisos.VENTAS_ANULAR,
      Permisos.VENTAS_REPORTES,
      Permisos.CAJA_VER_PROPIA,
      Permisos.CAJA_VER_TODAS,
      Permisos.CAJA_ARQUEO,
      Permisos.CAJA_SUPERVISAR_ARQUEO,
      Permisos.CAJA_MOVIMIENTOS,
      Permisos.CAJA_VER_HISTORIAL_TURNOS,
      Permisos.PRODUCTOS_VER,
      Permisos.PRODUCTOS_EDITAR,
      Permisos.PRODUCTOS_STOCK,
      Permisos.INVENTARIO_VER,
      Permisos.INVENTARIO_CONTEO,
      Permisos.INVENTARIO_SOLICITAR_AJUSTE,
      Permisos.INVENTARIO_APROBAR_AJUSTE,
      Permisos.INVENTARIO_AJUSTAR,
      Permisos.CLIENTES_VER,
      Permisos.CLIENTES_CREAR,
      Permisos.CLIENTES_EDITAR,
      Permisos.PROVEEDORES_VER,
      Permisos.COMPRAS_VER,
      Permisos.REPORTES_VER,
      Permisos.REPORTES_VENTAS_VER,
      Permisos.REPORTES_CAJA_VER,
      Permisos.ANALISIS_OPERATIVO_VER,
      Permisos.NOTIFICACIONES_VER,
      Permisos.RESTAURANTE_SALON_VER,
      Permisos.RESTAURANTE_SESION_ABRIR,
      Permisos.RESTAURANTE_SESION_ABANDONAR,
      Permisos.RESTAURANTE_SESION_CERRAR,
      Permisos.RESTAURANTE_SESION_LIBERAR_INCIDENCIA,
      Permisos.RESTAURANTE_PEDIDO_VER,
      Permisos.RESTAURANTE_PEDIDO_EDITAR,
      Permisos.RESTAURANTE_RONDA_ENVIAR,
      Permisos.RESTAURANTE_ENTREGA_CONFIRMAR,
      Permisos.RESTAURANTE_PREPARACION_VER,
      Permisos.RESTAURANTE_PREPARACION_ACTUALIZAR,
      Permisos.RESTAURANTE_CUENTA_VER,
      Permisos.RESTAURANTE_CUENTA_CONFIGURAR_REDONDEO,
      Permisos.RESTAURANTE_CUENTA_COBRAR,
      Permisos.PERSONAL_VER,
      Permisos.PERFIL_VER,
      Permisos.PERFIL_EDITAR,
    ],
  },
  [RolesPredefinidos.CAJERO]: {
    nombre: RolesPredefinidos.CAJERO,
    descripcion: "Caja, cobros y cierre de turno propio",
    permisos: [
      ...PERMISOS_IMPRESORAS_USO_UNIVERSAL,
      Permisos.DASHBOARD_VER,
      Permisos.DASHBOARD_OPERATIVO,
      Permisos.PUNTO_VENTA_VER,
      Permisos.PUNTO_VENTA_CREAR,
      Permisos.PUNTO_VENTA_BUSCAR_PRODUCTOS,
      Permisos.PUNTO_VENTA_ASIGNAR_CLIENTE,
      Permisos.PUNTO_VENTA_IMPRIMIR_COMPROBANTE,
      Permisos.PUNTO_VENTA_REIMPRIMIR_COMPROBANTE,
      Permisos.VENTAS_CREAR,
      Permisos.VENTAS_VER,
      Permisos.VENTAS_VER_PROPIAS,
      Permisos.VENTAS_VER_DETALLE,
      Permisos.CAJA_VER_PROPIA,
      Permisos.CAJA_ABRIR,
      Permisos.CAJA_CERRAR,
      Permisos.CAJA_CERRAR_PROPIA,
      Permisos.CAJA_ARQUEO,
      Permisos.CAJA_ARQUEO_PROPIO,
      Permisos.CAJA_MOVIMIENTOS,
      Permisos.CUENTAS_VER,
      Permisos.CUENTAS_VER_PROPIAS,
      Permisos.CUENTAS_REGISTRAR_PAGO,
      Permisos.CLIENTES_VER,
      Permisos.CLIENTES_CREAR,
      Permisos.PRODUCTOS_VER,
      Permisos.PRODUCTOS_STOCK,
      Permisos.PAGOS_VER,
      Permisos.RESTAURANTE_CUENTA_VER,
      Permisos.RESTAURANTE_CUENTA_CONFIGURAR_REDONDEO,
      Permisos.RESTAURANTE_CUENTA_COBRAR,
      Permisos.PERFIL_VER,
      Permisos.PERFIL_EDITAR,
    ],
  },
  [RolesPredefinidos.VENTAS]: {
    nombre: RolesPredefinidos.VENTAS,
    descripcion: "Atencion comercial, ventas y gestion basica de clientes",
    permisos: [
      ...PERMISOS_IMPRESORAS_USO_UNIVERSAL,
      Permisos.DASHBOARD_VER,
      Permisos.PUNTO_VENTA_VER,
      Permisos.PUNTO_VENTA_CREAR,
      Permisos.PUNTO_VENTA_BUSCAR_PRODUCTOS,
      Permisos.PUNTO_VENTA_PESAR_PRODUCTOS,
      Permisos.PUNTO_VENTA_ASIGNAR_CLIENTE,
      Permisos.PUNTO_VENTA_APLICAR_DESCUENTO,
      Permisos.PUNTO_VENTA_IMPRIMIR_COMPROBANTE,
      Permisos.VENTAS_CREAR,
      Permisos.VENTAS_VER,
      Permisos.VENTAS_VER_PROPIAS,
      Permisos.VENTAS_VER_DETALLE,
      Permisos.CLIENTES_VER,
      Permisos.CLIENTES_CREAR,
      Permisos.CLIENTES_EDITAR,
      Permisos.CLIENTES_VER_DETALLE,
      Permisos.PRODUCTOS_VER,
      Permisos.PERFIL_VER,
      Permisos.PERFIL_EDITAR,
    ],
  },
  [RolesPredefinidos.OPERACIONES]: {
    nombre: RolesPredefinidos.OPERACIONES,
    descripcion: "Operacion fisica, reposicion, despacho y apoyo de almacen",
    permisos: [
      ...PERMISOS_IMPRESORAS_USO_UNIVERSAL,
      Permisos.DASHBOARD_VER,
      Permisos.ALERTAS_VER,
      Permisos.PRODUCTOS_VER,
      Permisos.PRODUCTOS_STOCK,
      Permisos.INVENTARIO_VER,
      Permisos.INVENTARIO_VER_BASICO,
      Permisos.INVENTARIO_CONTEO,
      Permisos.INVENTARIO_REGISTRAR_MERMA,
      Permisos.ALMACENES_VER,
      Permisos.ALMACENES_VER_RECEPCIONES,
      Permisos.ALMACENES_VER_TRANSFERENCIAS,
      Permisos.UTILIDADES_MENU_PRINCIPAL,
      Permisos.PERFIL_VER,
    ],
  },
  [RolesPredefinidos.INVENTARIO]: {
    nombre: RolesPredefinidos.INVENTARIO,
    descripcion: "Control de stock, ajustes, mermas, almacenes y transferencias",
    permisos: [
      ...PERMISOS_IMPRESORAS_USO_UNIVERSAL,
      Permisos.DASHBOARD_VER,
      Permisos.ALERTAS_VER,
      Permisos.PRODUCTOS_VER,
      Permisos.PRODUCTOS_STOCK,
      Permisos.INVENTARIO_VER,
      Permisos.INVENTARIO_VER_TODOS_ALMACENES,
      Permisos.INVENTARIO_CONTEO,
      Permisos.INVENTARIO_SOLICITAR_AJUSTE,
      Permisos.INVENTARIO_APROBAR_AJUSTE,
      Permisos.INVENTARIO_AJUSTAR,
      Permisos.INVENTARIO_TRANSFERIR,
      Permisos.INVENTARIO_VER_MERMAS,
      Permisos.INVENTARIO_REGISTRAR_MERMA,
      Permisos.INVENTARIO_VER_HISTORIAL,
      Permisos.INVENTARIO_EXPORTAR,
      Permisos.ALMACENES_VER,
      Permisos.ALMACENES_CREAR_TRANSFERENCIA,
      Permisos.ALMACENES_VER_TRANSFERENCIAS,
      Permisos.ALMACENES_VER_RECEPCIONES,
      Permisos.REPORTES_INVENTARIO_VER,
      Permisos.PERFIL_VER,
      Permisos.PERFIL_EDITAR,
    ],
  },
  [RolesPredefinidos.COMPRAS]: {
    nombre: RolesPredefinidos.COMPRAS,
    descripcion: "Abastecimiento, proveedores, costos y recepcion de mercaderia",
    permisos: [
      ...PERMISOS_IMPRESORAS_USO_UNIVERSAL,
      Permisos.DASHBOARD_VER,
      Permisos.COMPRAS_VER,
      Permisos.COMPRAS_CREAR,
      Permisos.COMPRAS_EDITAR,
      Permisos.COMPRAS_APROBAR,
      Permisos.COMPRAS_RECEPCIONAR,
      Permisos.COMPRAS_VER_COSTOS,
      Permisos.COMPRAS_REGISTRAR_PAGO,
      Permisos.COMPRAS_VER_PAGOS,
      Permisos.COMPRAS_EXPORTAR,
      Permisos.PROVEEDORES_VER,
      Permisos.PROVEEDORES_CREAR,
      Permisos.PROVEEDORES_EDITAR,
      Permisos.PROVEEDORES_VER_DETALLE,
      Permisos.PROVEEDORES_VER_PAGOS,
      Permisos.PROVEEDORES_VER_HISTORIAL_COMPRAS,
      Permisos.ALMACENES_VER_RECEPCIONES,
      Permisos.ALMACENES_CREAR_RECEPCION,
      Permisos.REPORTES_COMPRAS_VER,
      Permisos.PERFIL_VER,
      Permisos.PERFIL_EDITAR,
    ],
  },
  [RolesPredefinidos.FINANZAS]: {
    nombre: RolesPredefinidos.FINANZAS,
    descripcion: "Control de ingresos, egresos, cuentas y caja historica",
    permisos: [
      ...PERMISOS_IMPRESORAS_USO_UNIVERSAL,
      Permisos.DASHBOARD_VER,
      Permisos.DASHBOARD_FINANCIERO,
      Permisos.FINANZAS_VER,
      Permisos.FINANZAS_CREAR,
      Permisos.FINANZAS_EDITAR,
      Permisos.FINANZAS_REPORTES,
      Permisos.CAJA_VER_TODAS,
      Permisos.CAJA_VER_HISTORIAL_TURNOS,
      Permisos.CUENTAS_VER,
      Permisos.CUENTAS_VER_TODAS,
      Permisos.CUENTAS_REGISTRAR_PAGO,
      Permisos.CUENTAS_AJUSTAR_DEUDA,
      Permisos.CUENTAS_VER_HISTORIAL,
      Permisos.CUENTAS_VER_MOROSIDAD,
      Permisos.PAGOS_VER,
      Permisos.PAGOS_VER_DIGITALES,
      Permisos.PAGOS_CONCILIAR,
      Permisos.REPORTES_VER,
      Permisos.REPORTES_FINANZAS_VER,
      Permisos.REPORTES_CAJA_VER,
      Permisos.ANALISIS_FINANCIERO_VER,
      Permisos.NOTIFICACIONES_VER_FINANCIERAS,
      Permisos.PERFIL_VER,
      Permisos.PERFIL_EDITAR,
    ],
  },
  [RolesPredefinidos.VENDEDOR]: {
    nombre: RolesPredefinidos.VENDEDOR,
    descripcion: "Rol legacy para apps antiguas; equivalente funcional a ventas",
    permisos: [
      ...PERMISOS_IMPRESORAS_USO_UNIVERSAL,
      Permisos.DASHBOARD_VER,
      Permisos.PUNTO_VENTA_VER,
      Permisos.PUNTO_VENTA_CREAR,
      Permisos.PUNTO_VENTA_BUSCAR_PRODUCTOS,
      Permisos.PUNTO_VENTA_ASIGNAR_CLIENTE,
      Permisos.VENTAS_CREAR,
      Permisos.VENTAS_VER,
      Permisos.VENTAS_VER_PROPIAS,
      Permisos.CLIENTES_CREAR,
      Permisos.CLIENTES_VER,
      Permisos.CLIENTES_EDITAR,
      Permisos.PRODUCTOS_VER,
      Permisos.PERFIL_VER,
      Permisos.PERFIL_EDITAR,
    ],
  },
  [RolesPredefinidos.CONTADOR]: {
    nombre: RolesPredefinidos.CONTADOR,
    descripcion: "Revision contable y financiera con acceso a exportaciones y reportes",
    permisos: [
      ...PERMISOS_IMPRESORAS_USO_UNIVERSAL,
      Permisos.DASHBOARD_VER,
      Permisos.DASHBOARD_FINANCIERO,
      Permisos.VENTAS_VER,
      Permisos.VENTAS_VER_TODAS,
      Permisos.VENTAS_REPORTES,
      Permisos.VENTAS_EXPORTAR,
      Permisos.CAJA_VER_TODAS,
      Permisos.CAJA_VER_HISTORIAL_TURNOS,
      Permisos.COMPRAS_VER,
      Permisos.COMPRAS_VER_COSTOS,
      Permisos.COMPRAS_VER_PAGOS,
      Permisos.FINANZAS_VER,
      Permisos.FINANZAS_REPORTES,
      Permisos.CUENTAS_VER,
      Permisos.CUENTAS_VER_TODAS,
      Permisos.CUENTAS_VER_HISTORIAL,
      Permisos.PROVEEDORES_VER,
      Permisos.CLIENTES_VER,
      Permisos.PAGOS_VER,
      Permisos.PAGOS_CONCILIAR,
      Permisos.REPORTES_VER,
      Permisos.REPORTES_VENTAS_VER,
      Permisos.REPORTES_CAJA_VER,
      Permisos.REPORTES_FINANZAS_VER,
      Permisos.REPORTES_COMPRAS_VER,
      Permisos.REPORTES_EXPORTAR,
      Permisos.ANALISIS_FINANCIERO_VER,
      Permisos.PERFIL_VER,
      Permisos.PERFIL_EDITAR,
    ],
  },
  [RolesPredefinidos.AUDITOR]: {
    nombre: RolesPredefinidos.AUDITOR,
    descripcion: "Revision de historial, auditoria y acciones sensibles sin operacion directa",
    permisos: [
      ...PERMISOS_IMPRESORAS_USO_UNIVERSAL,
      Permisos.DASHBOARD_VER,
      Permisos.VENTAS_VER,
      Permisos.VENTAS_VER_TODAS,
      Permisos.CAJA_VER_TODAS,
      Permisos.COMPRAS_VER,
      Permisos.INVENTARIO_VER,
      Permisos.USUARIOS_VER,
      Permisos.AUDITORIA_VER,
      Permisos.AUDITORIA_VER_ACCIONES_CRITICAS,
      Permisos.AUDITORIA_USUARIOS_VER,
      Permisos.AUDITORIA_CAJA_VER,
      Permisos.AUDITORIA_VENTAS_VER,
      Permisos.AUDITORIA_FINANZAS_VER,
      Permisos.RESTAURANTE_SALON_VER,
      Permisos.RESTAURANTE_PEDIDO_VER,
      Permisos.RESTAURANTE_PREPARACION_VER,
      Permisos.RESTAURANTE_CUENTA_VER,
      Permisos.REPORTES_VER,
      Permisos.NOTIFICACIONES_VER,
      Permisos.PERFIL_VER,
    ],
  },
  [RolesPredefinidos.SOPORTE_TECNICO]: {
    nombre: RolesPredefinidos.SOPORTE_TECNICO,
    descripcion: "Soporte tecnico, dispositivos, impresoras y configuracion operativa",
    permisos: [
      ...PERMISOS_IMPRESORAS_USO_UNIVERSAL,
      Permisos.DASHBOARD_VER,
      Permisos.UTILIDADES_VER,
      Permisos.UTILIDADES_USAR_CAMARA,
      Permisos.CONFIGURACION_VER,
      Permisos.CONFIGURACION_IMPRESORAS_VER,
      Permisos.CONFIGURACION_IMPRESORAS_EDITAR,
      Permisos.CONFIGURACION_SISTEMA_VER,
      Permisos.CONFIGURACION_INTEGRACIONES_VER,
      Permisos.RESTAURANTE_AMBIENTE_VER,
      Permisos.RESTAURANTE_AMBIENTE_CONFIGURAR,
      Permisos.RESTAURANTE_MESA_VER,
      Permisos.RESTAURANTE_MESA_CONFIGURAR,
      Permisos.RESTAURANTE_ESTACION_VER,
      Permisos.RESTAURANTE_ESTACION_CONFIGURAR,
      Permisos.RESTAURANTE_CARTA_VER,
      Permisos.RESTAURANTE_CARTA_CONFIGURAR,
      Permisos.NOTIFICACIONES_VER_SISTEMA,
      Permisos.PERFIL_VER,
      Permisos.PERFIL_EDITAR,
    ],
  },
  [RolesPredefinidos.SOLO_LECTURA]: {
    nombre: RolesPredefinidos.SOLO_LECTURA,
    descripcion: "Consulta autorizada sin crear, editar, anular ni aprobar registros",
    permisos: [
      ...PERMISOS_IMPRESORAS_USO_UNIVERSAL,
      Permisos.DASHBOARD_VER,
      Permisos.VENTAS_VER,
      Permisos.VENTAS_VER_DETALLE,
      Permisos.CAJA_VER_PROPIA,
      Permisos.PRODUCTOS_VER,
      Permisos.PRODUCTOS_STOCK,
      Permisos.CLIENTES_VER,
      Permisos.PROVEEDORES_VER,
      Permisos.PERSONAL_VER,
      Permisos.COMPRAS_VER,
      Permisos.INVENTARIO_VER,
      Permisos.REPORTES_VER,
      Permisos.NOTIFICACIONES_VER,
      Permisos.RESTAURANTE_SALON_VER,
      Permisos.RESTAURANTE_PEDIDO_VER,
      Permisos.RESTAURANTE_PREPARACION_VER,
      Permisos.RESTAURANTE_CUENTA_VER,
      Permisos.PERFIL_VER,
    ],
  },
  [RolesPredefinidos.GASTRONOMIA_ANFITRION]: {
    nombre: RolesPredefinidos.GASTRONOMIA_ANFITRION,
    descripcion: "Recepcion, disponibilidad de salon y apertura de atenciones",
    permisos: [
      Permisos.RESTAURANTE_SALON_VER,
      Permisos.RESTAURANTE_MESA_VER,
      Permisos.RESTAURANTE_SESION_ABRIR,
      Permisos.RESTAURANTE_SESION_ABANDONAR,
    ],
  },
  [RolesPredefinidos.GASTRONOMIA_MESERO]: {
    nombre: RolesPredefinidos.GASTRONOMIA_MESERO,
    descripcion: "Salon, pedido, rondas y entrega a mesa",
    permisos: [
      Permisos.RESTAURANTE_SALON_VER,
      Permisos.RESTAURANTE_MESA_VER,
      Permisos.RESTAURANTE_SESION_ABRIR,
      Permisos.RESTAURANTE_SESION_ABANDONAR,
      Permisos.RESTAURANTE_SESION_CERRAR,
      Permisos.RESTAURANTE_PEDIDO_VER,
      Permisos.RESTAURANTE_PEDIDO_EDITAR,
      Permisos.RESTAURANTE_RONDA_ENVIAR,
      Permisos.RESTAURANTE_ENTREGA_CONFIRMAR,
      Permisos.RESTAURANTE_CUENTA_VER,
    ],
  },
  [RolesPredefinidos.GASTRONOMIA_CAPITAN_SALON]: {
    nombre: RolesPredefinidos.GASTRONOMIA_CAPITAN_SALON,
    descripcion: "Supervision de atenciones e incidencias del salon",
    permisos: [
      Permisos.RESTAURANTE_SALON_VER,
      Permisos.RESTAURANTE_MESA_VER,
      Permisos.RESTAURANTE_SESION_ABRIR,
      Permisos.RESTAURANTE_SESION_ABANDONAR,
      Permisos.RESTAURANTE_SESION_CERRAR,
      Permisos.RESTAURANTE_SESION_LIBERAR_INCIDENCIA,
      Permisos.RESTAURANTE_PEDIDO_VER,
      Permisos.RESTAURANTE_PEDIDO_EDITAR,
      Permisos.RESTAURANTE_RONDA_ENVIAR,
      Permisos.RESTAURANTE_ENTREGA_CONFIRMAR,
      Permisos.RESTAURANTE_CUENTA_VER,
    ],
  },
  [RolesPredefinidos.GASTRONOMIA_COCINERO]: {
    nombre: RolesPredefinidos.GASTRONOMIA_COCINERO,
    descripcion: "Preparacion de comandas asignadas a Cocina",
    permisos: [
      Permisos.RESTAURANTE_PREPARACION_COCINA_VER,
      Permisos.RESTAURANTE_PREPARACION_COCINA_ACTUALIZAR,
    ],
  },
  [RolesPredefinidos.GASTRONOMIA_JEFE_COCINA]: {
    nombre: RolesPredefinidos.GASTRONOMIA_JEFE_COCINA,
    descripcion: "Supervision de preparacion en todas las estaciones",
    permisos: [
      Permisos.RESTAURANTE_PREPARACION_VER,
      Permisos.RESTAURANTE_PREPARACION_ACTUALIZAR,
      Permisos.RESTAURANTE_PREPARACION_COCINA_VER,
      Permisos.RESTAURANTE_PREPARACION_COCINA_ACTUALIZAR,
      Permisos.RESTAURANTE_PREPARACION_BARRA_VER,
      Permisos.RESTAURANTE_PREPARACION_BARRA_ACTUALIZAR,
    ],
  },
  [RolesPredefinidos.GASTRONOMIA_BARRA]: {
    nombre: RolesPredefinidos.GASTRONOMIA_BARRA,
    descripcion: "Preparacion de comandas asignadas a Barra",
    permisos: [
      Permisos.RESTAURANTE_PREPARACION_BARRA_VER,
      Permisos.RESTAURANTE_PREPARACION_BARRA_ACTUALIZAR,
    ],
  },
};
